### ISSUE TITLE
Discord-"Lite"

### ISSUE THREAD

**Issue by dx7v2** [therealcyber71/Discord-Lite#16]
I am installed discord lite on my windows 10 pc
and it was very "light" (%100 CPU, 172 processes, at least %75 ram usage)
![image](https://user-images.githubusercontent.com/107001892/173674661-7c22ee7d-d643-4f94-872a-64ae5b58e74c.png)

**Comment by therealcyber71** [comment]
lol, you must've installed version 1.1, there is a multi threading issue with v1.1 try v1.2 thanks

**Comment by therealcyber71** [comment]
https://github.com/therealcyber71/Discord-Lite/blob/main/installer/Discord-Lite-1.2.exe

download from this link

**Comment by dx7v2** [comment]
> https://github.com/therealcyber71/Discord-Lite/blob/main/installer/Discord-Lite-1.2.exe
> 
> download from this link

Where do you think I downloaded the discord lite from??

**Comment by therealcyber71** [comment]
idk an old link, v1.1 proabbly, if the issue still persists, I'm afraid I don't know what is wrong, since many users are quite okay with it's performance.

**Comment by dx7v2** [comment]
> idk an old link, v1.1 proabbly, if the issue still persists, I'm afraid I don't know what is wrong, since many users are quite okay with it's performance.

There is no performance, it crashes my computer without opening.
But thanks again for showing interest in my issue.
Bye, have a good day.

**Comment by therealcyber71** [comment]
> > idk an old link, v1.1 proabbly, if the issue still persists, I'm afraid I don't know what is wrong, since many users are quite okay with it's performance.
> 
> There is no performance, it crashes my computer without opening.
> But thanks again for showing interest in my issue.
> Bye, have a good day.

Just because it doesn't work on your PC doesn't mean it doesn't have a good performance, please try looking into the solution provided, if that's not possible try building a solution and offering constructive criticism, thank you and have a good day.

**Comment by therealcyber71** [comment]
![Screenshot_20220618-081102_GitHub.jpg](https://user-images.githubusercontent.com/72592470/174419454-85078e82-9335-47bf-8dad-240e7411da1f.jpg)
