### ISSUE TITLE
Add more options to the context menu

### ISSUE THREAD

**Issue by Ramzh** [therealcyber71/Discord-Lite#20]
Would it be possible to have more options in the context menu such as:
- Copy Image
- Copy Image URL

These are present in the official Discord client would be nice to have the same in this client too.

**Comment by therealcyber71** [comment]
Heya, thanks for reporting this issue, I'll let you know about this in the next release!

**Comment by therealcyber71** [comment]
Hi @Ramzh so I tested out all possible renderers given in the pywebview docs 
https://pywebview.flowrl.com/guide/renderer.html

none of them seem to give me a copy image and copy image link option like the original client, except pyqt5

the problem with pyqt5 is that it doesnt support debugging, hence making it impossible to solve javascript errors and it also cannot render video files and gifs

if you have any other rendering engine or an alternative to pywebview I'd love to hear about it!

**Comment by Ramzh** [comment]
Hey @therealcyber71 

Thanks for the reply and looking into it. Unfortunately I am not too familiar with pyqt5 nor webview and looking at the docs you seem to be right. 

I do not think as of yet it's possible unless writing the functions yourself somehow

**Comment by therealcyber71** [comment]
Hello @Ramzh the current webview options limit my ability to add custom functions, I will still be looking for alternatives.

I will now be closing the issue, if you do have any issues feel free to reopen the issue.
