### ISSUE TITLE
I was accidently deny microphone access

### ISSUE THREAD

**Issue by popos123** [therealcyber71/Discord-Lite#23]
in this case when im deny the microphone access (the popup from Webview2 runtime), I can't turn it ON back again.
How to do that?

**Comment by therealcyber71** [comment]
hello, which version of Discord Lite are you using?

**Comment by popos123** [comment]
The nevest - 1.3

**Comment by therealcyber71** [comment]
Hey, I currently can't find anything about permissions 8n the docs, I suggest you uninstall and then re-install thr current version.

Sorry for the inconvenience caused, this will be fixed in the next version.

**Comment by popos123** [comment]
Nope, still doesn't work. I suppose the temp / cache / cookies needs to clear.
But i don't know where it is stored from the Webview2.

**Comment by therealcyber71** [comment]
the usual discord folder I presume, gimme a day or two and I'll get back to you!

**Comment by dune-studios** [comment]
> Nope, still doesn't work. I suppose the temp / cache / cookies needs to clear. But i don't know where it is stored from the Webview2.

Do `windows key + R` to open the run page. Enter `%temp%` and that will open the temporary files folder. idk what one webview uses, so your on your own after that.

I hope I helped you!
TheCodeDoc

**Comment by dune-studios** [comment]
also the next best thing to do is open microsoft edge and change `https://discord.com`'s microphone permissions

**Comment by dune-studios** [comment]
cuz yknow webview is basically microsoft edge

**Comment by popos123** [comment]
I was fixed this bug by deleting the temp / config files from the Discord Lite in the **C:\Users\<user>\AppData\Local\pywebview** directory.
So please fix this in the next version of the Discord Lite.

**Comment by therealcyber71** [comment]
So this solves the issue? I will now be closing it then.
