### ISSUE TITLE
White Window Error 

### ISSUE THREAD

**Issue by AEKHer** [therealcyber71/Discord-Lite#33]
**How can i fix this?**

![image](https://user-images.githubusercontent.com/78161216/209478501-b88a3b74-76ee-4cd2-a852-71845a750ae1.png)

**Comment by therealcyber71** [comment]
> **How can i fix this?**
> 
> 
> ![image](https://user-images.githubusercontent.com/78161216/209478501-b88a3b74-76ee-4cd2-a852-71845a750ae1.png)

Please check other issues before opening a new one.
