### ISSUE TITLE
Owner Account Hacked/Compromised

### ISSUE THREAD

**Issue by softwarebycyber** [therealcyber71/Discord-Lite#37]
Hello everyone, I'm cyber's alt, my account was recently hacked by a bunch of turkish teens, I have no way to access my account since they changed my e-mail address. 

New changes cannot be made as of now to the repo, I have opened a ticket with github but I've heard they're slow to respond, so yeah we'll have to wait this one out, if you guys have any idea/solutions please  drop em below.

I also need to recover my organisations.

**Comment by softwarebycyber** [comment]
I would also suggest not to install the binaries provided now, since they could be compromised, I am guessing these "hackers" are going to sell the account, anyways stay safe everyone :)

**Comment by IntoTheVoid-900** [comment]
I suggest forking everything in its current state in case it is deleted and/or modified by the hackers.

**Comment by kocane** [comment]
@softwarebycyber Was your account compromised before the current release? I just installed it (and uninstalled again) because I didn't see your post before. Sorry to hear about your account, weird how Github doesn't react.

**Comment by softwarebycyber** [comment]
After the current release, the binaries haven't been changed for now

I know this because any change would be reflected on the discord webhooks setup in my server.

So you're good to go

Support server: https://discord.gg/5eebgq9CRk

**Comment by softwarebycyber** [comment]
Sorry for the inconvenience caused.

**Comment by softwarebycyber** [comment]
> I suggest forking everything in its current state in case it is deleted and/or modified by the hackers.

I didn't notice this

Nice idea, I've cloned the repo locally for now.

**Comment by softwarebycyber** [comment]
Invite link expired, here's the new link: https://discord.gg/JPcR5w6VZT

**Comment by softwarebycyber** [comment]
I have decided to move the repos development to this account since I'm pretty sure github won't recover my account.

Will post more updates here.

**Comment by softwarebycyber** [comment]
GitHub as miraculously contacted me within 20 days, and there might be hope for the account.

**Comment by therealcyber71** [comment]
Got my account back, thanks GitHub. I will be archiving this repo now.
